import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import FaviconCanvas from "../components/FaviconCanvas";

export const metadata: Metadata = {
  title: "mvm",
  description: "Generated by mvm",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="bg-black text-gray-100 text-[20px]"
    >
      <body className="antialiased">
        <TooltipProvider>
          <FaviconCanvas />
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
